version: '3'
services:
  app:
    build: .
    ports:
    - 3000:3000
    volumes:
    - .:/app
    depends_on:
    - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
