version: '3'
services:
  app:
    build: .
    ports:
    - 3000:3000
    volumes:
    - .:/app
    depends_on:
    - mysql
    - webpack

  webpack:
    build: .
    command: bin/webpack-dev-server
    ports:
    - 3035:3035
    volumes:
    - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
